CREATE TABLE PUBLIC.PUBLIC.CARGO (
	"TYPE" VARCHAR(100),
	NAME VARCHAR(100),
	WEIGHT INTEGER,
	EXPIRATIONDATE DATE,
	STORETEMPERATURE INTEGER,
	"SIZE" VARCHAR(100),
	MATERIAL VARCHAR(100),
	ID VARCHAR(100) NOT NULL
);

CREATE TABLE PUBLIC.PUBLIC.CARRIERS (
	ID VARCHAR(100) NOT NULL,
	NAME VARCHAR(100),
	ADDRESS VARCHAR(100),
	"TYPE" VARCHAR(100)
);


CREATE TABLE PUBLIC.PUBLIC.TRANSPORTATION (
	CARGOREF VARCHAR(100),
	CARRIERREF VARCHAR(100),
	BILLTO VARCHAR(100),
	BEGINDATE DATE,
	DESCRIPTION VARCHAR(100)
);
